help.pageSize=15
help.showNotes=true
help.builtInTitle=\u539f\u751f\u670d\u52a1\u7aef\u547d\u4ee4
help.pluginTitle=\u63d2\u4ef6\u547d\u4ee4

plugin.groups=restart,permission,listdata,wzmap,api,market,comid,comid-display,bindstate,bind,chat,landmine,help,skill,leaderboard,level,economy,anonymous,vote,foundation

plugin.group.restart.display=\u91cd\u542f\u8ba1\u5212
plugin.group.restart.prefixes=plan-restart-

plugin.group.permission.display=\u6743\u9650\u7ec4
plugin.group.permission.prefixes=permission-group-

plugin.group.listdata.display=\u5217\u8868\u6570\u636e\u7cfb\u7edf
plugin.group.listdata.prefixes=list-data-

plugin.group.wzmap.display=WZ\u5730\u56fe\u6865
plugin.group.wzmap.prefixes=wz-map-

plugin.group.api.display=API\u63a5\u53e3\u8c03\u7528
plugin.group.api.prefixes=api-call-

plugin.group.market.display=\u63d2\u4ef6\u5e02\u573a
plugin.group.market.prefixes=market-

plugin.group.comid.display=ComId \u751f\u6210
plugin.group.comid.prefixes=jump-comid-

plugin.group.comid-display.display=ComId \u663e\u793a
plugin.group.comid-display.prefixes=comid-display-

plugin.group.bindstate.display=\u5df2\u7ed1\u5b9a/\u672a\u7ed1\u5b9a
plugin.group.bindstate.prefixes=bind-state-

plugin.group.bind.display=QQ \u7ed1\u5b9a
plugin.group.bind.prefixes=bind-

plugin.group.chat.display=\u804a\u5929\u51fa\u5165
plugin.group.chat.prefixes=chat-access-

plugin.group.landmine.display=\u5730\u96f7\u6865
plugin.group.landmine.prefixes=jumpmine-

plugin.group.help.display=\u5e2e\u52a9\u7cfb\u7edf
plugin.group.help.prefixes=help-list-,help-ui-

plugin.group.skill.display=\u6280\u80fd\u547d\u4ee4
plugin.group.skill.prefixes=skill-customizer-

plugin.group.leaderboard.display=\u6392\u884c\u699c
plugin.group.leaderboard.prefixes=leaderboard-

plugin.group.level.display=\u73a9\u5bb6\u7b49\u7ea7
plugin.group.level.prefixes=level-

plugin.group.economy.display=\u73a9\u5bb6\u7ecf\u6d4e
plugin.group.economy.prefixes=economy-

plugin.group.anonymous.display=\u533f\u540d
plugin.group.anonymous.prefixes=anonymous-

plugin.group.vote.display=\u6295\u7968\u4f9d\u8d56
plugin.group.vote.prefixes=vote-dep-

plugin.group.foundation.display=\u57fa\u7840\u4e16\u754c\u63a7\u5236
plugin.group.foundation.prefixes=fwc-
