# 分页
帮助.每页最大命令数=15
帮助.分类策略=default
帮助.全部模式关键字=all
帮助.原版命令中文备注=true

# 颜色
帮助.页面标题颜色=[accent]
帮助.页面内容颜色=[white]
帮助.选中项颜色=[lime]
帮助.底部提示颜色=[lightgray]

# 交互键
交互.启用esc退出=true
交互.启用q退出=true
交互.启用感叹号快捷=true
交互.上一页按键=a
交互.下一页按键=s
交互.确认按键=enter,space

# 注册
注册.帮助备注语言=zh-CN
