help=查看帮助页
version=查看服务端版本信息
exit=立即退出服务器
host=托管当前地图
stop=停止服务器
maps=查看地图列表
reloadpatches=重新加载补丁文件
reloadmaps=重新加载地图
status=查看服务器状态
mods=查看已加载模组
mod=查看指定模组信息
js=执行后台 JavaScript
say=向所有玩家发送消息
pause=暂停或恢复游戏
rules=查看或修改全局规则
fillitems=给核心填满物资
playerlimit=设置服务器人数上限
config=修改服务器配置项
subnet-ban=按网段封禁
name-ban=按名称正则封禁
whitelist=维护白名单
shuffle=设置地图轮换模式
nextmap=指定下一张地图
kick=踢出指定玩家
ban=封禁指定玩家
bans=查看封禁列表
unban=解除封禁
pardon=解除投票踢出限制
admin=添加或移除管理员
admins=查看管理员列表
players=查看当前在线玩家
runwave=立即触发下一波
loadautosave=加载最近自动存档
load=读取指定存档
save=保存当前游戏进度
saves=查看所有存档
gameover=强制本局结束
info=查询玩家信息
search=按名称检索玩家
gc=手动执行垃圾回收
yes=执行上一条建议命令
dos-ban=维护 DOS 封禁列表
mdtreload=重新加载 serve-mdt 配置
